name: 'Record action run to Seekret snapshot'
description: 'Create a Seekret snapshot from a Github action run'

inputs:
  client_id:
    description: 'Client ID'
    required: true
  client_secret:
    description: 'Client secret'
    required: true
  workspace:
    description: 'Workspace'
    required: true
  anonymization:
    description: 'Should we anonymize traffic ("true" or "false")'
    required: false
    default: "true"
  auth_url:
    description: 'Auth URL'
    required: false
  sniffer_image_tag:
    description: 'Image tag of the sniffer to use'
    required: true
    default: "dev"

runs:
  using: "composite"
  steps:
    - name: Install Seekret CLI
      shell: bash
      run: |
        curl -L https://github.com/seek-ret/installation/releases/latest/download/install-seekret-linux-x86_64.sh | sh

    - name: Generate session token
      shell: bash
      env:
        SEEKRET_API_GATEWAY_URL: ${{ inputs.auth_url }}
      run: |
        ~/.seekret/seekret init -w ${{ inputs.workspace }} --client-id ${{ inputs.client_id }} --client-secret ${{ inputs.client_secret }}
        TOKEN=$(~/.seekret/seekret generate-session-token snapshot --plan $GITHUB_WORKFLOW)
        echo ::set-output name=session_token::"$TOKEN"

    - name: Run sniffer docker
      uses: seek-ret/seekret-sniffer-action@main
      with:
        client_id: ${{ inputs.client_id }}
        client_secret: ${{ inputs.client_secret }}
        workspace: ${{ inputs.workspace }}
        anonymization: ${{ inputs.anonymization }}
        auth_url: ${{ inputs.auth_url }}
        session_token: ${{ steps.vars.outputs.session_token }}