name: 'Record action run to Seekret snapshot'
description: 'Create a Seekret snapshot from a Github action run'

inputs:
  client_id:
    description: 'Client ID'
    required: true
  client_secret:
    description: 'Client secret'
    required: true
  workspace:
    description: 'Workspace'
    required: true
  anonymization:
    description: 'Should we anonymize traffic ("true" or "false")'
    required: false
    default: "true"
  auth_url:
    description: 'Auth URL'
    required: false
  sniffer_image_tag:
    description: 'Image tag of the sniffer to use'
    required: true
    default: "dev"

runs:
  using: "composite"
  steps:
    - name: Debugggggg
      shell: bash
      run: |
        env
        echo ${{ github.event.inputs.workspace }}
        echo ${{ github.event.inputs.client_id }}
        echo ${{ github.event.inputs.client_secret }}
        echo ${{ github.event.inputs }}

    - name: Install Seekret CLI
      shell: bash
      run: |
        curl -L https://github.com/seek-ret/installation/releases/latest/download/install-seekret-linux-x86_64.sh | sh

    - name: Generate session token
      shell: bash
      run: |
        ~/.seekret/seekret init -w ${{ github.event.inputs.workspace }} --client-id ${{ github.event.inputs.client_id }} --client-secret ${{ github.event.inputs.client_secret }}
        echo ::set-output name=session_token::"$(~/.seekret/seekret generate-session-token snapshot)"

    - name: Run sniffer docker
      uses: seek-ret/seekret-sniffer-action@main
      with:
        client_id: ${{ github.event.inputs.client_id }}
        client_secret: ${{ github.event.inputs.client_secret }}
        workspace: ${{ github.event.inputs.workspace }}
        anonymization: ${{ github.event.inputs.anonymization }}
        auth_url: ${{ github.event.inputs.auth_url }}
        session_token: ${{ steps.vars.outputs.session_token }}